swagger: '2.0'
info:
  description: |
    Filter Policy API allows clients to add, get, update and delete SXP domain filter policies. 
    
    <h2>Revision History</h2>
    <table font-family:monospace> 
    <tr valign=top style='border:solid #CCCCCC 1.0pt;mso-border-alt:solid #CCCCCC .75pt;background:#DEEDF7'><td><b>Revision #</b></td><td><b>Resource Version</b></td><td><b>Cisco ISE Version</b></td><td><b>Description</b></td></tr>
    <tr style= 'border-bottom:solid #CCCCCC 1.0pt'><td>0</td><td>1.0</td><td>3.0</td><td>Initial Cisco ISE Version</td></tr>
    <tr style= 'border-bottom:solid #CCCCCC 1.0pt;background:#f8f8f8'><td>1</td><td>1.1</td><td>3.2</td><td>Added Patch operation</td></tr>
    </table>
    <br><br>
    <h2>Resource Definition</h2>
    <table>
    <tr valign=top style='border:solid #CCCCCC 1.0pt;mso-border-alt:solid #CCCCCC .75pt;background:#DEEDF7'><td><b>Attribute</b></td><td><b>Type</b></td><td><b>Required</b></td><td><b>Description</b></td><td><b>Example Values</b></td></tr>
    <tr><td style='font-family:monospace'>name</td><td>String</td><td>Yes</td><td>Resource Name</td><td></td></tr>
    <tr valign=top style='background:#f8f8f8'><td style='font-family:monospace'>id</td><td>String</td><td>No</td><td>Resource UUID, mandatory for update</td><td></td></tr>
    <tr><td style='font-family:monospace'>description</td><td>String</td><td>No</td><td>Resource Description</td><td></td></tr>
    <tr style= 'background:#f8f8f8'><td style='font-family:monospace'>subnet</td><td>String</td><td>No</td><td>Subnet for filter policy (hostname is not supported). At least one of subnet or sgt or vn should be defined</td><td>subnetAddress</td></tr>
    <tr><td style='font-family:monospace'>sgt</td><td>String</td><td>No</td><td>SGT name or ID. At least one of subnet or sgt or vn should be defined</td><td>sgt</td></tr>
    <tr style= 'background:#f8f8f8'><td style='font-family:monospace'>vn</td><td>String</td><td>No</td><td>Virtual Network. At least one of subnet or sgt or vn should be defined</td><td>virtualNetwork</td></tr>
    <tr style= 'border-bottom:solid #CCCCCC 1.0pt'><td style='font-family:monospace'>domains</td><td>String</td><td>Yes</td><td>List of SXP Domains, separated with comma</td><td>Sxp Vpn Name</td></tr>
    </table>
    
  version: 1.0.0
  title: Filter Policy

tags:
- name: filterpolicy

paths:
  /ers/config/filterpolicy/{id}:
    get:
      tags: 
      - filterpolicy
      summary: Get filter policy by ID
      description:
        <p>This API allows the client to get a filter policy by ID.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: header
          name: HTTP X-CSRF-TOKEN Header
          type: string
          description: 
             Required Only if Enabled from GUI
              Example:- fetch
      responses: 
        200:
          description: OK
          schema:
            $ref: '#/definitions/filter'
    patch:
      tags: 
      - filterpolicy
      summary: Update part of the filter policy by ID
      description:
        <p>This API allows the user to update part of the filter policy by ID.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: body
          name: request
          schema:
            $ref: '#/definitions/patchRequest'
      responses: 
        200:
          description: OK
          schema:
            $ref: '#/definitions/filter'  
            
            
    put:
      tags:
      - filterpolicy
      summary: Update filter policy
      description:  <p>This API allows the client to update a filter policy.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: header
          name: HTTP X-CSRF-TOKEN Header
          type: string
          description: 
               The Token value from the GET X-CSRF-TOKEN fetch request
        - in: body
          name: request
          schema:
            $ref: '#/definitions/filter'
      responses: 
        200:
          description: OK
          schema:
            $ref: '#/definitions/Update'  

    delete:
      tags:
      - filterpolicy
      summary: Delete filter policy
      description:
        <p>This API deletes a filter policy.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: header
          name: HTTP X-CSRF-TOKEN Header
          type: string
          description: 
               The Token value from the GET X-CSRF-TOKEN fetch request
      responses: 
        204:
          description: No content    
          
  /ers/config/filterpolicy:

    get:
      tags: 
      - filterpolicy
      summary: Get all filter policies
      description:
        <p>This API allows the client to get all the filter policies.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: header
          name: HTTP X-CSRF-TOKEN Header
          type: string
          description: 
             Required Only if Enabled from GUI
             Example:- fetch
      responses: 
        200:
          description: OK
          schema:
            $ref: '#/definitions/search'  
            
    post:
      tags:
      - filterpolicy
      summary: Create filter policy
      description:
        <p>This API creates a filter policy.</p>
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
        - in: header
          name: HTTP ERS-Media-Type Header
          type: string
          description: 
              Example:- sxp.filterpolicy.1.0
          required: false
        - in: header
          name: HTTP X-CSRF-TOKEN Header
          type: string
          description: 
               The Token value from the GET X-CSRF-TOKEN fetch request
          required: false
        - in: body
          name: request
          schema:
            $ref: '#/definitions/filter'
      responses:
        201:
          description: Created

  /ers/config/filterpolicy/versioninfo:
    get:
      tags:
      - filterpolicy
      summary: Get filter policy version information
      description:
        <p>This API helps to retrieve the version information related to the filter policy.</p>
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/VersionInfo'
            
definitions:
  filter:
    type: object
    properties:
      ERSFilterPolicy:
        $ref: '#/definitions/ERSFilterPolicy'
        
  ERSFilterPolicy:
    type: object
    properties:
      subnet:
        type: string
        example: subnetAddress
      domains:
        type: string
        example: Sxp Vpn Name
      sgt:
        type: string
        example: sgt
      vn:
        type: string
        example: virtualNetwork
  
  patchRequest:
    type: object
    properties:
      ERSFilterPolicy:
        $ref: '#/definitions/patchRequestBody'	
        
  patchRequestBody:
    type: object
    properties:
      any-resource-attribute:
        type: string
        example: some-updated-value
      another-resource-attribute:
        type: string
        example: some-updated-value 
  Update:
    type: object
    properties:
      UpdatedFieldsList:
        $ref: '#/definitions/UpdatedFieldsList'
        
  UpdatedFieldsList:
    type: object
    properties:
      updatedField:
         $ref: '#/definitions/UpdatedField'
      field:
        type: string
        example: some other field
      oldValue:
        type: string
        example: val_old
      newValue:
        type: string
        example: val_new
        
  UpdatedField:
    type: object
    properties:
      field:
        type: string
        example: field1
      oldValue:
        type: string
        example: val_old
      newValue:
        type: string
        example: val_new   

  search:
    type: object
    properties:
      SearchResult:
        $ref: '#/definitions/SearchResult'
        
  SearchResult:   
    type: object
    properties:
      total:
        type: integer
        example: 2
      resources:
        type: array
        example: [{"id" : "id1", "name" : "name1", "description" : "description1"}, {"id" : "id2", "name" : "name2", "description" : "description2"}]
        items:
          properties:
            name:
              type: string
      nextPage:
        type: array
        example: [{"rel" : "next", "href" : "link-to-next-page", "type" : "application/xml"}]
        items:
          properties:
            name:
              type: string
      previousPage:
        type: array
        example: [{"rel" : "previous", "href" : "link-to-previous-page", "type" : "application/xml"}]
        items:
          properties:
            name:
              type: string  
              
  VersionInfo:
    type: object
    properties:
      VersionInfo:
        $ref: '#/definitions/version'
        
  version:
    type: object
    properties:
      currentServerVersion:
        type: string
        example: "1.0"
      supportedVersions:
        type: string
        example: "1.0"  
      link:
        $ref: '#/definitions/link1'
        
  link1:
    type: object
    properties:
      rel:
        type: string
        example: self
      href:
        type: string
        example: https://<ise-ip>:9060/ers/config/filterpolicy/versioninfo
      type:
        type: string
        example: application/json
